spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bavilivre
    username: shahin
    password:
    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
