INSERT INTO users (id, display_name)
VALUES (1, 'Shahin');

INSERT INTO users (id, display_name)
VALUES (2, 'Alice');

INSERT INTO users (id, display_name)
VALUES (3, 'Bob');

ALTER TABLE users
    ALTER COLUMN id RESTART WITH 4;

INSERT INTO books (id,
                   owner_id,
                   title,
                   author,
                   description,
                   language,
                   category,
                   available,
                   archived,
                   created_at)
VALUES (1,
        1,
        'Clean Code',
        'Robert C. Martin',
        'A practical guide to writing clean and maintainable code.',
        'en',
        'Software Engineering',
        true,
        false,
        TIMESTAMP '2026-07-01 10:00:00');

INSERT INTO books (id,
                   owner_id,
                   title,
                   author,
                   description,
                   language,
                   category,
                   available,
                   archived,
                   created_at)
VALUES (2,
        1,
        'Domain-Driven Design',
        'Eric Evans',
        'A reference book about domain-driven design.',
        'en',
        'Software Architecture',
        true,
        false,
        TIMESTAMP '2026-06-01 10:00:00');

INSERT INTO books (id,
                   owner_id,
                   title,
                   author,
                   description,
                   language,
                   category,
                   available,
                   archived,
                   created_at)
VALUES (3,
        3,
        'Refactoring',
        'Martin Fowler',
        'Improving the design of existing code.',
        'en',
        'Software Engineering',
        true,
        false,
        TIMESTAMP '2026-06-11 10:00:00');

INSERT INTO books (id,
                   owner_id,
                   title,
                   author,
                   description,
                   language,
                   category,
                   available,
                   archived,
                   created_at)
VALUES (4,
        2,
        'Effective Java',
        'Joshua Bloch',
        'Best practices for writing robust Java applications.',
        'en',
        'Software Engineering',
        true,
        false,
        TIMESTAMP '2026-07-02 10:00:00'),

       (5,
        3,
        'Clean Architecture',
        'Robert C. Martin',
        'A guide to designing maintainable software systems.',
        'en',
        'Software Architecture',
        true,
        false,
        TIMESTAMP '2026-07-03 10:00:00'),

       (6,
        1,
        'Design Patterns',
        'Erich Gamma',
        'Classic object-oriented design patterns.',
        'en',
        'Software Architecture',
        false,
        false,
        TIMESTAMP '2026-07-04 10:00:00'),

       (7,
        2,
        'Spring Boot en pratique',
        'Julien Dubois',
        'Develop modern backend applications with Spring Boot.',
        'fr',
        'Software Engineering',
        true,
        false,
        TIMESTAMP '2026-07-05 10:00:00'),

       (8,
        3,
        'Architecture logicielle moderne',
        'Philippe Kruchten',
        'Principles of scalable software architecture.',
        'fr',
        'Software Architecture',
        true,
        false,
        TIMESTAMP '2026-07-06 10:00:00'),

       (9,
        1,
        'Développement Web avec Angular',
        'Nicolas Fränkel',
        'Build modern frontend applications with Angular.',
        'fr',
        'Web Development',
        true,
        false,
        TIMESTAMP '2026-07-07 10:00:00'),

       (10,
        2,
        'Base de données relationnelles',
        'Georges Gardarin',
        'Introduction to relational database concepts.',
        'fr',
        'Databases',
        false,
        false,
        TIMESTAMP '2026-07-08 10:00:00'),

       (11,
        3,
        'Java Grundlagen',
        'Klaus Moser',
        'Grundlagen der Java Programmierung.',
        'de',
        'Software Engineering',
        true,
        false,
        TIMESTAMP '2026-07-09 10:00:00'),

       (12,
        1,
        'Softwarearchitektur verstehen',
        'Gernot Starke',
        'Einführung in moderne Softwarearchitektur.',
        'de',
        'Software Architecture',
        true,
        false,
        TIMESTAMP '2026-07-10 10:00:00'),

       (13,
        2,
        'Webentwicklung mit Angular',
        'Sebastian Springer',
        'Moderne Webentwicklung mit Angular.',
        'de',
        'Web Development',
        false,
        false,
        TIMESTAMP '2026-07-11 10:00:00'),

       (14,
        3,
        'Datenbanken und SQL',
        'Andreas Meier',
        'Grundlagen von Datenbanken und SQL.',
        'de',
        'Databases',
        true,
        false,
        TIMESTAMP '2026-07-12 10:00:00'),

       (15,
        1,
        'مهندسی نرم افزار',
        'رضا تقی زاده',
        'اصول طراحی و توسعه نرم افزار.',
        'fa',
        'Software Engineering',
        true,
        false,
        TIMESTAMP '2026-07-13 10:00:00'),

       (16,
        2,
        'معماری نرم افزار',
        'علی احمدی',
        'مفاهیم معماری سیستم های نرم افزاری.',
        'fa',
        'Software Architecture',
        true,
        false,
        TIMESTAMP '2026-07-14 10:00:00'),

       (17,
        3,
        'توسعه وب مدرن',
        'محمد رضایی',
        'راهنمای توسعه برنامه های وب مدرن.',
        'fa',
        'Web Development',
        false,
        false,
        TIMESTAMP '2026-07-15 10:00:00'),

       (18,
        1,
        'Docker & Kubernetes',
        'Kelsey Hightower',
        'Containerization and cloud deployment practices.',
        'en',
        'DevOps',
        true,
        false,
        TIMESTAMP '2026-07-16 10:00:00'),

       (19,
        2,
        'CI/CD avec GitLab',
        'Nicolas Dille',
        'Continuous integration and deployment workflows.',
        'fr',
        'DevOps',
        true,
        false,
        TIMESTAMP '2026-07-17 10:00:00'),

       (20,
        3,
        'Terraform in Action',
        'Scott Winkler',
        'Infrastructure as code with Terraform.',
        'en',
        'DevOps',
        false,
        false,
        TIMESTAMP '2026-07-18 10:00:00'),

       (21,
        1,
        'SQL Performance Explained',
        'Markus Winand',
        'Improve database query performance.',
        'en',
        'Databases',
        true,
        false,
        TIMESTAMP '2026-07-19 10:00:00'),

       (22,
        2,
        'The Pragmatic Programmer',
        'Andrew Hunt',
        'Practical advice for software developers.',
        'en',
        'Software Engineering',
        true,
        false,
        TIMESTAMP '2026-07-20 10:00:00');

INSERT INTO books (id,
                   owner_id,
                   title,
                   author,
                   description,
                   language,
                   category,
                   available,
                   archived,
                   created_at)
VALUES (23,
        3,
        'Java Concurrency in Practice',
        'Brian Goetz',
        'A guide to writing concurrent applications in Java.',
        'en',
        'Software Engineering',
        true,
        false,
        TIMESTAMP '2026-07-21 10:00:00'),

       (24,
        1,
        'Spring in Action',
        'Craig Walls',
        'Building enterprise applications with Spring Framework.',
        'en',
        'Software Engineering',
        true,
        false,
        TIMESTAMP '2026-07-22 10:00:00'),

       (25,
        2,
        'Microservices Patterns',
        'Chris Richardson',
        'Patterns and best practices for microservice architecture.',
        'en',
        'Software Architecture',
        false,
        false,
        TIMESTAMP '2026-07-23 10:00:00'),

       (26,
        3,
        'Kubernetes Patterns',
        'Bilgin Ibryam',
        'Design patterns for cloud native applications.',
        'en',
        'DevOps',
        true,
        false,
        TIMESTAMP '2026-07-24 10:00:00'),

       (27,
        1,
        'Git avancé',
        'Vincent Driessen',
        'Maîtriser Git et les workflows collaboratifs.',
        'fr',
        'DevOps',
        true,
        false,
        TIMESTAMP '2026-07-25 10:00:00'),

       (28,
        2,
        'Tests logiciels avec JUnit',
        'Mickael Grenon',
        'Écrire des tests fiables avec Java et JUnit.',
        'fr',
        'Software Engineering',
        true,
        false,
        TIMESTAMP '2026-07-26 10:00:00'),

       (29,
        3,
        'UML et conception objet',
        'Pascal Roques',
        'Modélisation UML et conception des systèmes.',
        'fr',
        'Software Architecture',
        false,
        false,
        TIMESTAMP '2026-07-27 10:00:00'),

       (30,
        1,
        'React et les architectures frontend',
        'Sébastien Chopin',
        'Modern frontend development approaches.',
        'fr',
        'Web Development',
        true,
        false,
        TIMESTAMP '2026-07-28 10:00:00'),

       (31,
        2,
        'SQL Grundlagen',
        'Rainer Stropek',
        'Grundlagen relationaler Datenbanken.',
        'de',
        'Databases',
        true,
        false,
        TIMESTAMP '2026-07-29 10:00:00'),

       (32,
        3,
        'Professionelle Softwareentwicklung',
        'Gernot Starke',
        'Methoden und Werkzeuge für professionelle Entwickler.',
        'de',
        'Software Engineering',
        true,
        false,
        TIMESTAMP '2026-07-30 10:00:00'),

       (33,
        1,
        'Cloud Native Anwendungen',
        'Eberhard Wolff',
        'Architektur moderner Cloud Anwendungen.',
        'de',
        'Software Architecture',
        false,
        false,
        TIMESTAMP '2026-07-31 10:00:00'),

       (34,
        2,
        'Linux für Entwickler',
        'Michael Kofler',
        'Linux Grundlagen für Softwareentwickler.',
        'de',
        'DevOps',
        true,
        false,
        TIMESTAMP '2026-08-01 10:00:00'),

       (35,
        3,
        'برنامه نویسی جاوا',
        'علی حسینی',
        'آموزش برنامه نویسی جاوا از پایه.',
        'fa',
        'Software Engineering',
        true,
        false,
        TIMESTAMP '2026-08-02 10:00:00'),

       (36,
        1,
        'طراحی معماری نرم افزار',
        'محمد رضایی',
        'اصول طراحی معماری نرم افزارهای بزرگ.',
        'fa',
        'Software Architecture',
        true,
        false,
        TIMESTAMP '2026-08-03 10:00:00'),

       (37,
        2,
        'توسعه وب با انگولار',
        'سارا احمدی',
        'راهنمای توسعه برنامه های وب مدرن.',
        'fa',
        'Web Development',
        false,
        false,
        TIMESTAMP '2026-08-04 10:00:00'),

       (38,
        3,
        'مدیریت پایگاه داده',
        'رضا کریمی',
        'مفاهیم پایگاه داده و SQL.',
        'fa',
        'Databases',
        true,
        false,
        TIMESTAMP '2026-08-05 10:00:00'),

       (39,
        1,
        'Angular Complete Guide',
        'Maximilian Schwarzmüller',
        'Complete guide for Angular applications.',
        'en',
        'Web Development',
        true,
        false,
        TIMESTAMP '2026-08-06 10:00:00'),

       (40,
        2,
        'Vue.js Design Patterns',
        'Eduardo San Martin',
        'Frontend patterns and best practices.',
        'en',
        'Web Development',
        false,
        false,
        TIMESTAMP '2026-08-07 10:00:00'),

       (41,
        3,
        'PostgreSQL High Performance',
        'Gregory Smith',
        'Optimization techniques for PostgreSQL databases.',
        'en',
        'Databases',
        true,
        false,
        TIMESTAMP '2026-08-08 10:00:00'),

       (42,
        1,
        'Clean Code en pratique',
        'Robert C. Martin',
        'Application des principes Clean Code au quotidien.',
        'fr',
        'Software Engineering',
        true,
        false,
        TIMESTAMP '2026-08-09 10:00:00');

ALTER TABLE books
    ALTER COLUMN id RESTART WITH 43;

INSERT INTO borrowings (id,
                        book_id,
                        borrower_id,
                        lender_id,
                        borrowed_at,
                        returned_at)
VALUES (1,
        1,
        2,
        1,
        CURRENT_DATE,
        NULL);

INSERT INTO borrowings (id,
                        book_id,
                        borrower_id,
                        lender_id,
                        borrowed_at,
                        returned_at)
VALUES (2,
        3,
        1,
        3,
        CURRENT_DATE,
        NULL);

INSERT INTO user_accounts (user_id,
                           email,
                           password_hash)
VALUES (1,
        'shahinbavili@gmail.com',
        '$2a$10$iLrF2bg6gKPLag/3ZTpjve1ZUIGdDLivAy1Fpcm99jEElsvoJsZou');

INSERT INTO user_accounts (user_id,
                           email,
                           password_hash)
VALUES (2,
        'alice@bavilivre.dev',
        'password');

INSERT INTO user_accounts (user_id,
                           email,
                           password_hash)
VALUES (3,
        'bob@bavilivre.dev',
        'password');